# Generated by Django 5.1.5 on 2025-01-23 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('model', models.CharField(max_length=100, verbose_name='модель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=255, verbose_name='улица')),
                ('house', models.CharField(max_length=10, verbose_name='дом')),
                ('level', models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], verbose_name='уровень')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='задолженность поставщику')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('supplier_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.supplier', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
