# Generated by Django 5.1.5 on 2025-01-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_supplier_products_alter_supplier_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='web.product', verbose_name='продукты'),
        ),
    ]
