# Generated by Django 5.1.5 on 2025-01-23 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_supplier_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='products',
        ),
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.product', verbose_name='продукты'),
        ),
    ]
