# Generated by Django 5.1.5 on 2025-01-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_supplier_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='products',
        ),
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='web.product', verbose_name='продукты'),
        ),
    ]
