# Generated by Django 5.1.5 on 2025-01-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_supplier_products_supplier_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(to='web.product', verbose_name='продукты'),
        ),
    ]
