# Generated by Django 5.1.5 on 2025-01-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_supplier_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(default=None, to='web.product', verbose_name='продукты'),
        ),
    ]
